name: On Push
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v6       

      - name: Checkout cache
        id: cache_check
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('package-lock.json') }}
          lookup-only: true
          
      - name: Skip new cache        
        if: steps.cache_check.outputs.cache-hit == 'true'
        run: # exit_with_success
                
      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - uses: actions/cache/save@v5
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('package-lock.json') }}
        
  linter:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        
      - uses: actions/cache/restore@v5
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        
      - name: Run linting
        run: ng lint
        
  tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: ng test --no-watch
        
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: ng build
    
